### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vladdeSV** [TheArkive/JXON_ahk2#2]
I would like to use this in an open-source project of mine, and possibly improve on this library.

I cannot do that because there is no license attached.

**Comment by TheArkive** [comment]
Ok, I'll fix that.

**Comment by TheArkive** [comment]
Done.  Let me know if there's an issue with the license for your uses.

**Comment by vladdeSV** [comment]
Hello. Thank you for your quick response.

I see you modified the WTFPL license, but the second condition is unreasonable to be put in this license.
> 2. Give credit where credit is due. Not just to the author but to contributors also.

I hope you understand that the license allows anyone to change the license, completely disregarding whichever terms and conditions which come with the license.

Furthermore (sorry for hammering down so much on this issue, but licensing is a topic close to my heart), what is deemed "giving someone credit", and what is considered a "contributor"? This is vague and should be described without any doubt in the license.

In my personal opinion, I would stay away from WTFPL<sup><a href="http://cubicspot.blogspot.com/2017/04/wtfpl-is-harmful-to-software-developers.html">1</a>, <a href="https://news.ycombinator.com/item?id=6930005">2</a>, <a href="https://forum.minetest.net/viewtopic.php?t=15354">3</a></sup>, and use some other recognized license, such as [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (similar to WTFPL, but more legally grounded).

If you insist on using WTFPL, I highly suggest you do not change the license yourself<sup><a href="https://opensource.stackexchange.com/a/252">4</a></sup>.

---

Sorry for my rant. If you decide to keep this license, I will take this code and change the license to some other license, most likely the [MIT](https://opensource.org/licenses/MIT) license.

**Comment by TheArkive** [comment]
Thanks for your links.  That was educational.  I will switch it to the MIT license.

**Comment by TheArkive** [comment]
BTW, just wanted to add that the original author of the AHK v1 version went with the WTFPL, and me, not being well versed in software licenses figured it was reasonable to stay with that.

As much as I am frustrated with the "stuffiness" of the legal side of these things (as one of your links put it), I do want to take my projects at least serious enough so that more people can use the stuff that I create without pause.

I appreciate the brevity of the MIT license, so you'll see that on more of my projects going forward in case you see more stuff you want to incorporate.

**Comment by vladdeSV** [comment]
Great to hear that. I, too, used WTFPL in the past, not realizing the implications of it.

Looking forward to your upcoming projects.
